#
# ███████╗████████╗ █████╗ ██████╗ ███████╗██╗  ██╗██╗██████╗
# ██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██║  ██║██║██╔══██╗
# ███████╗   ██║   ███████║██████╔╝███████╗███████║██║██████╔╝
# ╚════██║   ██║   ██╔══██║██╔══██╗╚════██║██╔══██║██║██╔═══╝
# ███████║   ██║   ██║  ██║██║  ██║███████║██║  ██║██║██║
# ╚══════╝   ╚═╝   ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚═╝  ╚═╝╚═╝╚═╝
#
# Starship Config File by Arfan Zubi

# Get editor completions based on the config schema
"$schema" = "https://starship.rs/config-schema.json"

format = "$directory$character"
right_format = "$all"

palette = "catppuccin_mocha"
add_newline = false

[character]
format = "$symbol  "
success_symbol = "[\uf178](bold mauve)"
error_symbol = "[\uf178](bold red)"
vimcmd_symbol = "[\ue7c5](bold green)"
vimcmd_replace_one_symbol = "[\ue7c5](bold purple)"
vimcmd_replace_symbol = "[\ue7c5](bold purple)"
vimcmd_visual_symbol = "[\ue7c5](bold yellow)"

[directory]
format = "[\uf07b](bold blue) [$path]($style)[$read_only]($read_only_style) "
style = "bold blue"
read_only = " 󰌾"

[git_branch]
style = "bold red"


[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"
